version: "3.3"
services:
  postgres:
    image: "postgres:${POSTGRES_VERSION}"
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_VERSION}
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: monitoring_prometheus
#    restart: unless-stopped
#    volumes:
#      - ./data/prometheus/config:/prometheus/
#      - ./data/prometheus/data:/prometheus/data
#    command:
#      - '-config.file=/prometheus/prometheus.yml'
#      - '-storage.local.path=/prometheus'
#      - '-alertmanager.url=http://alertmanager:9093'
#    expose:
#      - 9090
#    ports:
#      - 9090:9090
#  grafana:
#    image: grafana/grafana:latest
#    container_name: monitoring_grafana
#    links:
#      - prometheus:prometheus
#    volumes:
#      - ./prometheus/grafana:/var/lib/grafana
#    ports:
#      - 3000:3000
volumes:
  postgres:
