INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin', 'BTC', 'Bitcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Ethereum', 'ETH', 'Ethereum');
INSERT INTO currencies (name, ticker, description) VALUES ('Tether', 'USDT', 'Tether');
INSERT INTO currencies (name, ticker, description) VALUES ('Cardano', 'ADA', 'Cardano');
INSERT INTO currencies (name, ticker, description) VALUES ('XRP', 'XRP', 'XRP');
INSERT INTO currencies (name, ticker, description) VALUES ('Polkadot', 'DOT', 'Polkadot');
INSERT INTO currencies (name, ticker, description) VALUES ('Binance Coin', 'BNB', 'Binance Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Litecoin', 'LTC', 'Litecoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Chainlink', 'LINK', 'Chainlink');
INSERT INTO currencies (name, ticker, description) VALUES ('Dogecoin', 'DOGE', 'Dogecoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin Cash', 'BCH', 'Bitcoin Cash');
INSERT INTO currencies (name, ticker, description) VALUES ('Stellar', 'XLM', 'Stellar');
INSERT INTO currencies (name, ticker, description) VALUES ('USD Coin', 'USDC', 'USD Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Aave', 'AAVE', 'Aave');
INSERT INTO currencies (name, ticker, description) VALUES ('Uniswap', 'UNI', 'Uniswap');
INSERT INTO currencies (name, ticker, description) VALUES ('Wrapped Bitcoin', 'WBTC', 'Wrapped Bitcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Avalanche', 'AVAX', 'Avalanche');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin SV', 'BSV', 'Bitcoin SV');
INSERT INTO currencies (name, ticker, description) VALUES ('EOS', 'EOS', 'EOS');
INSERT INTO currencies (name, ticker, description) VALUES ('TRON', 'TRX', 'TRON');
INSERT INTO currencies (name, ticker, description) VALUES ('NEM', 'XEM', 'NEM');
INSERT INTO currencies (name, ticker, description) VALUES ('Elrond', 'EGLD', 'Elrond');
INSERT INTO currencies (name, ticker, description) VALUES ('Cosmos', 'ATOM', 'Cosmos');
INSERT INTO currencies (name, ticker, description) VALUES ('Monero', 'XMR', 'Monero');
INSERT INTO currencies (name, ticker, description) VALUES ('Terra', 'LUNA', 'Terra');
INSERT INTO currencies (name, ticker, description) VALUES ('Synthetix', 'SNX', 'Synthetix');
INSERT INTO currencies (name, ticker, description) VALUES ('Tezos', 'XTZ', 'Tezos');
INSERT INTO currencies (name, ticker, description) VALUES ('THETA', 'THETA', 'THETA');
INSERT INTO currencies (name, ticker, description) VALUES ('Huobi Token', 'HT', 'Huobi Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Maker', 'MKR', 'Maker');
INSERT INTO currencies (name, ticker, description) VALUES ('Neo', 'NEO', 'Neo');
INSERT INTO currencies (name, ticker, description) VALUES ('VeChain', 'VET', 'VeChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Compound', 'COMP', 'Compound');
INSERT INTO currencies (name, ticker, description) VALUES ('IOTA', 'MIOTA', 'IOTA');
INSERT INTO currencies (name, ticker, description) VALUES ('Solana', 'SOL', 'Solana');
INSERT INTO currencies (name, ticker, description) VALUES ('Filecoin', 'FIL', 'Filecoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Dai', 'DAI', 'Dai');
INSERT INTO currencies (name, ticker, description) VALUES ('FTX Token', 'FTT', 'FTX Token');
INSERT INTO currencies (name, ticker, description) VALUES ('SushiSwap', 'SUSHI', 'SushiSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Binance USD', 'BUSD', 'Binance USD');
INSERT INTO currencies (name, ticker, description) VALUES ('Crypto.com Coin', 'CRO', 'Crypto.com Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('UMA', 'UMA', 'UMA');
INSERT INTO currencies (name, ticker, description) VALUES ('Celsius', 'CEL', 'Celsius');
INSERT INTO currencies (name, ticker, description) VALUES ('UNUS SED LEO', 'LEO', 'UNUS SED LEO');
INSERT INTO currencies (name, ticker, description) VALUES ('The Graph', 'GRT', 'The Graph');
INSERT INTO currencies (name, ticker, description) VALUES ('Dash', 'DASH', 'Dash');
INSERT INTO currencies (name, ticker, description) VALUES ('Algorand', 'ALGO', 'Algorand');
INSERT INTO currencies (name, ticker, description) VALUES ('yearn.finance', 'YFI', 'yearn.finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Zcash', 'ZEC', 'Zcash');
INSERT INTO currencies (name, ticker, description) VALUES ('Decred', 'DCR', 'Decred');
INSERT INTO currencies (name, ticker, description) VALUES ('Ethereum Classic', 'ETC', 'Ethereum Classic');
INSERT INTO currencies (name, ticker, description) VALUES ('0x', 'ZRX', '0x');
INSERT INTO currencies (name, ticker, description) VALUES ('BitTorrent', 'BTT', 'BitTorrent');
INSERT INTO currencies (name, ticker, description) VALUES ('Kusama', 'KSM', 'Kusama');
INSERT INTO currencies (name, ticker, description) VALUES ('Zilliqa', 'ZIL', 'Zilliqa');
INSERT INTO currencies (name, ticker, description) VALUES ('Revain', 'REV', 'Revain');
INSERT INTO currencies (name, ticker, description) VALUES ('Waves', 'WAVES', 'Waves');
INSERT INTO currencies (name, ticker, description) VALUES ('Nexo', 'NEXO', 'Nexo');
INSERT INTO currencies (name, ticker, description) VALUES ('Celo', 'CELO', 'Celo');
INSERT INTO currencies (name, ticker, description) VALUES ('NEAR Protocol', 'NEAR', 'NEAR Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Ren', 'REN', 'Ren');
INSERT INTO currencies (name, ticker, description) VALUES ('Loopring', 'LRC', 'Loopring');
INSERT INTO currencies (name, ticker, description) VALUES ('renBTC', 'RENBTC', 'renBTC');
INSERT INTO currencies (name, ticker, description) VALUES ('SwissBorg', 'CHSB', 'SwissBorg');
INSERT INTO currencies (name, ticker, description) VALUES ('Hedera Hashgraph', 'HBAR', 'Hedera Hashgraph');
INSERT INTO currencies (name, ticker, description) VALUES ('OMG Network', 'OMG', 'OMG Network');
INSERT INTO currencies (name, ticker, description) VALUES ('PancakeSwap', 'CAKE', 'PancakeSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Ontology', 'ONT', 'Ontology');
INSERT INTO currencies (name, ticker, description) VALUES ('THORChain', 'RUNE', 'THORChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Paxos Standard', 'PAX', 'Paxos Standard');
INSERT INTO currencies (name, ticker, description) VALUES ('Qtum', 'QTUM', 'Qtum');
INSERT INTO currencies (name, ticker, description) VALUES ('DigiByte', 'DGB', 'DigiByte');
INSERT INTO currencies (name, ticker, description) VALUES ('Curve DAO Token', 'CRV', 'Curve DAO Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Matic Network', 'MATIC', 'Matic Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Basic Attention Token', 'BAT', 'Basic Attention Token');
INSERT INTO currencies (name, ticker, description) VALUES ('1inch', '1INCH', '1inch');
INSERT INTO currencies (name, ticker, description) VALUES ('Nano', 'NANO', 'Nano');
INSERT INTO currencies (name, ticker, description) VALUES ('Voyager Token', 'VGX', 'Voyager Token');
INSERT INTO currencies (name, ticker, description) VALUES ('OKB', 'OKB', 'OKB');
INSERT INTO currencies (name, ticker, description) VALUES ('ICON', 'ICX', 'ICON');
INSERT INTO currencies (name, ticker, description) VALUES ('Reserve Rights', 'RSR', 'Reserve Rights');
INSERT INTO currencies (name, ticker, description) VALUES ('Quant', 'QNT', 'Quant');
INSERT INTO currencies (name, ticker, description) VALUES ('Siacoin', 'SC', 'Siacoin');
INSERT INTO currencies (name, ticker, description) VALUES ('HUSD', 'HUSD', 'HUSD');
INSERT INTO currencies (name, ticker, description) VALUES ('HedgeTrade', 'HEDG', 'HedgeTrade');
INSERT INTO currencies (name, ticker, description) VALUES ('Horizen', 'ZEN', 'Horizen');
INSERT INTO currencies (name, ticker, description) VALUES ('Kyber Network', 'KNC', 'Kyber Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin BEP2', 'BTCB', 'Bitcoin BEP2');
INSERT INTO currencies (name, ticker, description) VALUES ('Ampleforth', 'AMPL', 'Ampleforth');
INSERT INTO currencies (name, ticker, description) VALUES ('Stacks', 'STX', 'Stacks');
INSERT INTO currencies (name, ticker, description) VALUES ('TrueUSD', 'TUSD', 'TrueUSD');
INSERT INTO currencies (name, ticker, description) VALUES ('Ravencoin', 'RVN', 'Ravencoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Decentraland', 'MANA', 'Decentraland');
INSERT INTO currencies (name, ticker, description) VALUES ('IOST', 'IOST', 'IOST');
INSERT INTO currencies (name, ticker, description) VALUES ('Alpha Finance Lab', 'ALPHA', 'Alpha Finance Lab');
INSERT INTO currencies (name, ticker, description) VALUES ('Energy Web Token', 'EWT', 'Energy Web Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus', 'XVS', 'Venus');
INSERT INTO currencies (name, ticker, description) VALUES ('Fantom', 'FTM', 'Fantom');
INSERT INTO currencies (name, ticker, description) VALUES ('Enjin Coin', 'ENJ', 'Enjin Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Ocean Protocol', 'OCEAN', 'Ocean Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Bancor', 'BNT', 'Bancor');
INSERT INTO currencies (name, ticker, description) VALUES ('Verge', 'XVG', 'Verge');
INSERT INTO currencies (name, ticker, description) VALUES ('TerraUSD', 'UST', 'TerraUSD');
INSERT INTO currencies (name, ticker, description) VALUES ('Lisk', 'LSK', 'Lisk');
INSERT INTO currencies (name, ticker, description) VALUES ('Balancer', 'BAL', 'Balancer');
INSERT INTO currencies (name, ticker, description) VALUES ('Band Protocol', 'BAND', 'Band Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Augur', 'REP', 'Augur');
INSERT INTO currencies (name, ticker, description) VALUES ('Flow (Dapper Labs)', 'FLOW', 'Flow (Dapper Labs)');
INSERT INTO currencies (name, ticker, description) VALUES ('Helium', 'HNT', 'Helium');
INSERT INTO currencies (name, ticker, description) VALUES ('Status', 'SNT', 'Status');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin Gold', 'BTG', 'Bitcoin Gold');
INSERT INTO currencies (name, ticker, description) VALUES ('FunFair', 'FUN', 'FunFair');
INSERT INTO currencies (name, ticker, description) VALUES ('KuCoin Token', 'KCS', 'KuCoin Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Kava.io', 'KAVA', 'Kava.io');
INSERT INTO currencies (name, ticker, description) VALUES ('Injective Protocol', 'INJ', 'Injective Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Arweave', 'AR', 'Arweave');
INSERT INTO currencies (name, ticker, description) VALUES ('Aragon', 'ANT', 'Aragon');
INSERT INTO currencies (name, ticker, description) VALUES ('Theta Fuel', 'TFUEL', 'Theta Fuel');
INSERT INTO currencies (name, ticker, description) VALUES ('NuCypher', 'NU', 'NuCypher');
INSERT INTO currencies (name, ticker, description) VALUES ('Numeraire', 'NMR', 'Numeraire');
INSERT INTO currencies (name, ticker, description) VALUES ('Pundi X', 'NPXS', 'Pundi X');
INSERT INTO currencies (name, ticker, description) VALUES ('Swipe', 'SXP', 'Swipe');
INSERT INTO currencies (name, ticker, description) VALUES ('Gnosis', 'GNO', 'Gnosis');
INSERT INTO currencies (name, ticker, description) VALUES ('Serum', 'SRM', 'Serum');
INSERT INTO currencies (name, ticker, description) VALUES ('Nervos Network', 'CKB', 'Nervos Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Holo', 'HOT', 'Holo');
INSERT INTO currencies (name, ticker, description) VALUES ('RSK Infrastructure Framework', 'RIF', 'RSK Infrastructure Framework');
INSERT INTO currencies (name, ticker, description) VALUES ('Golem', 'GLM', 'Golem');
INSERT INTO currencies (name, ticker, description) VALUES ('Fetch.ai', 'FET', 'Fetch.ai');
INSERT INTO currencies (name, ticker, description) VALUES ('ZB Token', 'ZB', 'ZB Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Telcoin', 'TEL', 'Telcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Harmony', 'ONE', 'Harmony');
INSERT INTO currencies (name, ticker, description) VALUES ('Orchid', 'OXT', 'Orchid');
INSERT INTO currencies (name, ticker, description) VALUES ('MaidSafeCoin', 'MAID', 'MaidSafeCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Civic', 'CVC', 'Civic');
INSERT INTO currencies (name, ticker, description) VALUES ('Morpheus.Network', 'MRPH', 'Morpheus.Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Secret', 'SCRT', 'Secret');
INSERT INTO currencies (name, ticker, description) VALUES ('IoTeX', 'IOTX', 'IoTeX');
INSERT INTO currencies (name, ticker, description) VALUES ('Chiliz', 'CHZ', 'Chiliz');
INSERT INTO currencies (name, ticker, description) VALUES ('Vai', 'VAI', 'Vai');
INSERT INTO currencies (name, ticker, description) VALUES ('BitShares', 'BTS', 'BitShares');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin Diamond', 'BCD', 'Bitcoin Diamond');
INSERT INTO currencies (name, ticker, description) VALUES ('Utrust', 'UTK', 'Utrust');
INSERT INTO currencies (name, ticker, description) VALUES ('Oasis Network', 'ROSE', 'Oasis Network');
INSERT INTO currencies (name, ticker, description) VALUES ('TomoChain', 'TOMO', 'TomoChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Storj', 'STORJ', 'Storj');
INSERT INTO currencies (name, ticker, description) VALUES ('Mainframe', 'MFT', 'Mainframe');
INSERT INTO currencies (name, ticker, description) VALUES ('MonaCoin', 'MONA', 'MonaCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('ABBC Coin', 'ABBC', 'ABBC Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('OriginTrail', 'TRAC', 'OriginTrail');
INSERT INTO currencies (name, ticker, description) VALUES ('iExec RLC', 'RLC', 'iExec RLC');
INSERT INTO currencies (name, ticker, description) VALUES ('Bytom', 'BTM', 'Bytom');
INSERT INTO currencies (name, ticker, description) VALUES ('Stratis', 'STRAX', 'Stratis');
INSERT INTO currencies (name, ticker, description) VALUES ('PAX Gold', 'PAXG', 'PAX Gold');
INSERT INTO currencies (name, ticker, description) VALUES ('Unibright', 'UBT', 'Unibright');
INSERT INTO currencies (name, ticker, description) VALUES ('Ankr', 'ANKR', 'Ankr');
INSERT INTO currencies (name, ticker, description) VALUES ('district0x', 'DNT', 'district0x');
INSERT INTO currencies (name, ticker, description) VALUES ('CyberVein', 'CVT', 'CyberVein');
INSERT INTO currencies (name, ticker, description) VALUES ('aelf', 'ELF', 'aelf');
INSERT INTO currencies (name, ticker, description) VALUES ('Akropolis', 'AKRO', 'Akropolis');
INSERT INTO currencies (name, ticker, description) VALUES ('Gemini Dollar', 'GUSD', 'Gemini Dollar');
INSERT INTO currencies (name, ticker, description) VALUES ('SingularityNET', 'AGI', 'SingularityNET');
INSERT INTO currencies (name, ticker, description) VALUES ('Ardor', 'ARDR', 'Ardor');
INSERT INTO currencies (name, ticker, description) VALUES ('Haven Protocol', 'XHV', 'Haven Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Steem', 'STEEM', 'Steem');
INSERT INTO currencies (name, ticker, description) VALUES ('xDai', 'STAKE', 'xDai');
INSERT INTO currencies (name, ticker, description) VALUES ('Komodo', 'KMD', 'Komodo');
INSERT INTO currencies (name, ticker, description) VALUES ('Reef', 'REEF', 'Reef');
INSERT INTO currencies (name, ticker, description) VALUES ('Wanchain', 'WAN', 'Wanchain');
INSERT INTO currencies (name, ticker, description) VALUES ('JUST', 'JST', 'JUST');
INSERT INTO currencies (name, ticker, description) VALUES ('ReddCoin', 'RDD', 'ReddCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('TrustSwap', 'SWAP', 'TrustSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('MX Token', 'MX', 'MX Token');
INSERT INTO currencies (name, ticker, description) VALUES ('IRISnet', 'IRIS', 'IRISnet');
INSERT INTO currencies (name, ticker, description) VALUES ('saffron.finance', 'SFI', 'saffron.finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Tellor', 'TRB', 'Tellor');
INSERT INTO currencies (name, ticker, description) VALUES ('Populous', 'PPT', 'Populous');
INSERT INTO currencies (name, ticker, description) VALUES ('DFI.Money', 'YFII', 'DFI.Money');
INSERT INTO currencies (name, ticker, description) VALUES ('Velas', 'VLX', 'Velas');
INSERT INTO currencies (name, ticker, description) VALUES ('Wrapped NXM', 'WNXM', 'Wrapped NXM');
INSERT INTO currencies (name, ticker, description) VALUES ('Kin', 'KIN', 'Kin');
INSERT INTO currencies (name, ticker, description) VALUES ('VeThor Token', 'VTHO', 'VeThor Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Aidos Kuneen', 'ADK', 'Aidos Kuneen');
INSERT INTO currencies (name, ticker, description) VALUES ('Origin Protocol', 'OGN', 'Origin Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Travala.com', 'AVA', 'Travala.com');
INSERT INTO currencies (name, ticker, description) VALUES ('Energi', 'NRG', 'Energi');
INSERT INTO currencies (name, ticker, description) VALUES ('LTO Network', 'LTO', 'LTO Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Polymath', 'POLY', 'Polymath');
INSERT INTO currencies (name, ticker, description) VALUES ('Celer Network', 'CELR', 'Celer Network');
INSERT INTO currencies (name, ticker, description) VALUES ('COTI', 'COTI', 'COTI');
INSERT INTO currencies (name, ticker, description) VALUES ('Unifi Protocol DAO', 'UNFI', 'Unifi Protocol DAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Divi', 'DIVI', 'Divi');
INSERT INTO currencies (name, ticker, description) VALUES ('Syntropy', 'NOIA', 'Syntropy');
INSERT INTO currencies (name, ticker, description) VALUES ('bZx Protocol', 'BZRX', 'bZx Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Hive', 'HIVE', 'Hive');
INSERT INTO currencies (name, ticker, description) VALUES ('DIA', 'DIA', 'DIA');
INSERT INTO currencies (name, ticker, description) VALUES ('Ark', 'ARK', 'Ark');
INSERT INTO currencies (name, ticker, description) VALUES ('StormX', 'STMX', 'StormX');
INSERT INTO currencies (name, ticker, description) VALUES ('SUN', 'SUN', 'SUN');
INSERT INTO currencies (name, ticker, description) VALUES ('CertiK', 'CTK', 'CertiK');
INSERT INTO currencies (name, ticker, description) VALUES ('HEX', 'HEX', 'HEX');
INSERT INTO currencies (name, ticker, description) VALUES ('Counos X', 'CCXX', 'Counos X');
INSERT INTO currencies (name, ticker, description) VALUES ('INO COIN', 'INO', 'INO COIN');
INSERT INTO currencies (name, ticker, description) VALUES ('DeFiChain', 'DFI', 'DeFiChain');
INSERT INTO currencies (name, ticker, description) VALUES ('ThoreCoin', 'THR', 'ThoreCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Creditcoin', 'CTC', 'Creditcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Insight Chain', 'INB', 'Insight Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('botXcoin', 'BOTX', 'botXcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('IZE', 'IZE', 'IZE');
INSERT INTO currencies (name, ticker, description) VALUES ('NXM', 'NXM', 'NXM');
INSERT INTO currencies (name, ticker, description) VALUES ('Wrapped BNB', 'WBNB', 'Wrapped BNB');
INSERT INTO currencies (name, ticker, description) VALUES ('Bridge Oracle', 'BRG', 'Bridge Oracle');
INSERT INTO currencies (name, ticker, description) VALUES ('GNY', 'GNY', 'GNY');
INSERT INTO currencies (name, ticker, description) VALUES ('Zelwin', 'ZLW', 'Zelwin');
INSERT INTO currencies (name, ticker, description) VALUES ('Strong', 'STRONG', 'Strong');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin Cash ABC', 'BCHA', 'Bitcoin Cash ABC');
INSERT INTO currencies (name, ticker, description) VALUES ('SafePal', 'SFP', 'SafePal');
INSERT INTO currencies (name, ticker, description) VALUES ('Cipher Core Token', 'CIPHC', 'Cipher Core Token');
INSERT INTO currencies (name, ticker, description) VALUES ('DerivaDAO', 'DDX', 'DerivaDAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitpanda Ecosystem Token', 'BEST', 'Bitpanda Ecosystem Token');
INSERT INTO currencies (name, ticker, description) VALUES ('stETH (Lido)', 'STETH', 'stETH (Lido)');
INSERT INTO currencies (name, ticker, description) VALUES ('Basid Coin', 'BASID', 'Basid Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Huobi BTC', 'HBTC', 'Huobi BTC');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus BNB', 'vBNB', 'Venus BNB');
INSERT INTO currencies (name, ticker, description) VALUES ('WhiteCoin', 'XWC', 'WhiteCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Badger DAO', 'BADGER', 'Badger DAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus BTC', 'vBTC', 'Venus BTC');
INSERT INTO currencies (name, ticker, description) VALUES ('The Transfer Token', 'TTT', 'The Transfer Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Keep Network', 'KEEP', 'Keep Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Largo Coin', 'LRG', 'Largo Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Linear', 'LINA', 'Linear');
INSERT INTO currencies (name, ticker, description) VALUES ('BitMax Token', 'BTMX', 'BitMax Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Elitium', 'EUM', 'Elitium');
INSERT INTO currencies (name, ticker, description) VALUES ('Sologenic', 'SOLO', 'Sologenic');
INSERT INTO currencies (name, ticker, description) VALUES ('Trust Wallet Token', 'TWT', 'Trust Wallet Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirror Protocol', 'MIR', 'Mirror Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Perpetual Protocol', 'PERP', 'Perpetual Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Amp', 'AMP', 'Amp');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus XVS', 'vXVS', 'Venus XVS');
INSERT INTO currencies (name, ticker, description) VALUES ('MimbleWimbleCoin', 'MWC', 'MimbleWimbleCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('ZKSwap', 'ZKS', 'ZKSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Doctors Coin', 'DRS', 'Doctors Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Eauric', 'EAURIC', 'Eauric');
INSERT INTO currencies (name, ticker, description) VALUES ('YUSRA', 'YUSRA', 'YUSRA');
INSERT INTO currencies (name, ticker, description) VALUES ('Cream Finance', 'CREAM', 'Cream Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Neutrino USD', 'USDN', 'Neutrino USD');
INSERT INTO currencies (name, ticker, description) VALUES ('sUSD', 'SUSD', 'sUSD');
INSERT INTO currencies (name, ticker, description) VALUES ('Harvest Finance', 'FARM', 'Harvest Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Hegic', 'HEGIC', 'Hegic');
INSERT INTO currencies (name, ticker, description) VALUES ('Polkastarter', 'POLS', 'Polkastarter');
INSERT INTO currencies (name, ticker, description) VALUES ('Idea Chain Coin', 'ICH', 'Idea Chain Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('PARSIQ', 'PRQ', 'PARSIQ');
INSERT INTO currencies (name, ticker, description) VALUES ('SKALE Network', 'SKL', 'SKALE Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Gala', 'GALA', 'Gala');
INSERT INTO currencies (name, ticker, description) VALUES ('Litentry', 'LIT', 'Litentry');
INSERT INTO currencies (name, ticker, description) VALUES ('Mobilian Coin', 'MBN', 'Mobilian Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('NewYork Exchange', 'NYE', 'NewYork Exchange');
INSERT INTO currencies (name, ticker, description) VALUES ('Akash Network', 'AKT', 'Akash Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Bloomzed Loyalty Club Ticket', 'BLCT', 'Bloomzed Loyalty Club Ticket');
INSERT INTO currencies (name, ticker, description) VALUES ('Edgeware', 'EDG', 'Edgeware');
INSERT INTO currencies (name, ticker, description) VALUES ('Hellenic Coin', 'HNC', 'Hellenic Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('XinFin Network', 'XDC', 'XinFin Network');
INSERT INTO currencies (name, ticker, description) VALUES ('GreenPower', 'GRN', 'GreenPower');
INSERT INTO currencies (name, ticker, description) VALUES ('Vitae', 'VITAE', 'Vitae');
INSERT INTO currencies (name, ticker, description) VALUES ('Cashaa', 'CAS', 'Cashaa');
INSERT INTO currencies (name, ticker, description) VALUES ('Massnet', 'MASS', 'Massnet');
INSERT INTO currencies (name, ticker, description) VALUES ('XeniosCoin', 'XNC', 'XeniosCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Bytecoin', 'BCN', 'Bytecoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Orion Protocol', 'ORN', 'Orion Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Chimpion', 'BNANA', 'Chimpion');
INSERT INTO currencies (name, ticker, description) VALUES ('DIGG', 'DIGG', 'DIGG');
INSERT INTO currencies (name, ticker, description) VALUES ('The Sandbox', 'SAND', 'The Sandbox');
INSERT INTO currencies (name, ticker, description) VALUES ('MATH', 'MATH', 'MATH');
INSERT INTO currencies (name, ticker, description) VALUES ('Beefy.Finance', 'BIFI', 'Beefy.Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Mixin', 'XIN', 'Mixin');
INSERT INTO currencies (name, ticker, description) VALUES ('Sapphire', 'SAPP', 'Sapphire');
INSERT INTO currencies (name, ticker, description) VALUES ('Folgory Coin', 'FLG', 'Folgory Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('DuckDaoDime', 'DDIM', 'DuckDaoDime');
INSERT INTO currencies (name, ticker, description) VALUES ('NEST Protocol', 'NEST', 'NEST Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Empty Set Dollar', 'ESD', 'Empty Set Dollar');
INSERT INTO currencies (name, ticker, description) VALUES ('Frax', 'FRAX', 'Frax');
INSERT INTO currencies (name, ticker, description) VALUES ('HARD Protocol', 'HARD', 'HARD Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Beldex', 'BDX', 'Beldex');
INSERT INTO currencies (name, ticker, description) VALUES ('TNC Coin', 'TNC', 'TNC Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('API3', 'API3', 'API3');
INSERT INTO currencies (name, ticker, description) VALUES ('CoinMetro Token', 'XCM', 'CoinMetro Token');
INSERT INTO currencies (name, ticker, description) VALUES ('AXEL', 'AXEL', 'AXEL');
INSERT INTO currencies (name, ticker, description) VALUES ('Spartan Protocol', 'SPARTA', 'Spartan Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Poseidon Network', 'QQQ', 'Poseidon Network');
INSERT INTO currencies (name, ticker, description) VALUES ('WAX', 'WAXP', 'WAX');
INSERT INTO currencies (name, ticker, description) VALUES ('Syscoin', 'SYS', 'Syscoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Livepeer', 'LPT', 'Livepeer');
INSERT INTO currencies (name, ticker, description) VALUES ('Qcash', 'QC', 'Qcash');
INSERT INTO currencies (name, ticker, description) VALUES ('BarnBridge', 'BOND', 'BarnBridge');
INSERT INTO currencies (name, ticker, description) VALUES ('Enzyme', 'MLN', 'Enzyme');
INSERT INTO currencies (name, ticker, description) VALUES ('Metacoin', 'MTC', 'Metacoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Keep3rV1', 'KP3R', 'Keep3rV1');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus ETH', 'vETH', 'Venus ETH');
INSERT INTO currencies (name, ticker, description) VALUES ('DODO', 'DODO', 'DODO');
INSERT INTO currencies (name, ticker, description) VALUES ('Opium', 'OPIUM', 'Opium');
INSERT INTO currencies (name, ticker, description) VALUES ('Rakon', 'RKN', 'Rakon');
INSERT INTO currencies (name, ticker, description) VALUES ('GateToken', 'GT', 'GateToken');
INSERT INTO currencies (name, ticker, description) VALUES ('AdEx Network', 'ADX', 'AdEx Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Attila', 'ATT', 'Attila');
INSERT INTO currencies (name, ticker, description) VALUES ('Sport and Leisure', 'SNL', 'Sport and Leisure');
INSERT INTO currencies (name, ticker, description) VALUES ('Rari Governance Token', 'RGT', 'Rari Governance Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Loom Network', 'LOOM', 'Loom Network');
INSERT INTO currencies (name, ticker, description) VALUES ('LBRY Credits', 'LBC', 'LBRY Credits');
INSERT INTO currencies (name, ticker, description) VALUES ('Sora', 'XOR', 'Sora');
INSERT INTO currencies (name, ticker, description) VALUES ('Handshake ', 'HNS', 'Handshake ');
INSERT INTO currencies (name, ticker, description) VALUES ('Atari Token', 'ATRI', 'Atari Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Zenon', 'ZNN', 'Zenon');
INSERT INTO currencies (name, ticker, description) VALUES ('Meta', 'MTA', 'Meta');
INSERT INTO currencies (name, ticker, description) VALUES ('Elastos', 'ELA', 'Elastos');
INSERT INTO currencies (name, ticker, description) VALUES ('AllianceBlock', 'ALBT', 'AllianceBlock');
INSERT INTO currencies (name, ticker, description) VALUES ('Ultra', 'UOS', 'Ultra');
INSERT INTO currencies (name, ticker, description) VALUES ('DxChain Token', 'DX', 'DxChain Token');
INSERT INTO currencies (name, ticker, description) VALUES ('NFTX', 'NFTX', 'NFTX');
INSERT INTO currencies (name, ticker, description) VALUES ('Uquid Coin', 'UQC', 'Uquid Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('KardiaChain', 'KAI', 'KardiaChain');
INSERT INTO currencies (name, ticker, description) VALUES ('WINk', 'WIN', 'WINk');
INSERT INTO currencies (name, ticker, description) VALUES ('Electroneum', 'ETN', 'Electroneum');
INSERT INTO currencies (name, ticker, description) VALUES ('PAID Network', 'PAID', 'PAID Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Power Ledger', 'POWR', 'Power Ledger');
INSERT INTO currencies (name, ticker, description) VALUES ('BakeryToken', 'BAKE', 'BakeryToken');
INSERT INTO currencies (name, ticker, description) VALUES ('Flamingo', 'FLM', 'Flamingo');
INSERT INTO currencies (name, ticker, description) VALUES ('Hxro', 'HXRO', 'Hxro');
INSERT INTO currencies (name, ticker, description) VALUES ('SparkPoint', 'SRK', 'SparkPoint');
INSERT INTO currencies (name, ticker, description) VALUES ('Dent', 'DENT', 'Dent');
INSERT INTO currencies (name, ticker, description) VALUES ('Darma Cash', 'DMCH', 'Darma Cash');
INSERT INTO currencies (name, ticker, description) VALUES ('TROY', 'TROY', 'TROY');
INSERT INTO currencies (name, ticker, description) VALUES ('QuarkChain', 'QKC', 'QuarkChain');
INSERT INTO currencies (name, ticker, description) VALUES ('WaykiChain', 'WICC', 'WaykiChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Bella Protocol', 'BEL', 'Bella Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Request', 'REQ', 'Request');
INSERT INTO currencies (name, ticker, description) VALUES ('EFFORCE', 'WOZX', 'EFFORCE');
INSERT INTO currencies (name, ticker, description) VALUES ('Firo', 'FIRO', 'Firo');
INSERT INTO currencies (name, ticker, description) VALUES ('STASIS EURO', 'EURS', 'STASIS EURO');
INSERT INTO currencies (name, ticker, description) VALUES ('PowerPool', 'CVP', 'PowerPool');
INSERT INTO currencies (name, ticker, description) VALUES ('Everipedia', 'IQ', 'Everipedia');
INSERT INTO currencies (name, ticker, description) VALUES ('Ergo', 'ERG', 'Ergo');
INSERT INTO currencies (name, ticker, description) VALUES ('Rocket Pool', 'RPL', 'Rocket Pool');
INSERT INTO currencies (name, ticker, description) VALUES ('Axie Infinity', 'AXS', 'Axie Infinity');
INSERT INTO currencies (name, ticker, description) VALUES ('Tornado Cash', 'TORN', 'Tornado Cash');
INSERT INTO currencies (name, ticker, description) VALUES ('TrueFi', 'TRU', 'TrueFi');
INSERT INTO currencies (name, ticker, description) VALUES ('Streamr', 'DATA', 'Streamr');
INSERT INTO currencies (name, ticker, description) VALUES ('MINDOL', 'MIN', 'MINDOL');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus BUSD', 'vBUSD', 'Venus BUSD');
INSERT INTO currencies (name, ticker, description) VALUES ('cVault.finance', 'CORE', 'cVault.finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Tokenlon Network Token', 'LON', 'Tokenlon Network Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Etherisc DIP Token', 'DIP', 'Etherisc DIP Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Ferrum Network', 'FRM', 'Ferrum Network');
INSERT INTO currencies (name, ticker, description) VALUES ('BTU Protocol', 'BTU', 'BTU Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('ankrETH', 'aEth', 'ankrETH');
INSERT INTO currencies (name, ticker, description) VALUES ('Rewardiqa', 'REW', 'Rewardiqa');
INSERT INTO currencies (name, ticker, description) VALUES ('Dragonchain', 'DRGN', 'Dragonchain');
INSERT INTO currencies (name, ticker, description) VALUES ('DAO Maker', 'DAO', 'DAO Maker');
INSERT INTO currencies (name, ticker, description) VALUES ('Aion', 'AION', 'Aion');
INSERT INTO currencies (name, ticker, description) VALUES ('MXC', 'MXC', 'MXC');
INSERT INTO currencies (name, ticker, description) VALUES ('pNetwork', 'PNT', 'pNetwork');
INSERT INTO currencies (name, ticker, description) VALUES ('Bluzelle', 'BLZ', 'Bluzelle');
INSERT INTO currencies (name, ticker, description) VALUES ('Huobi Pool Token', 'HPT', 'Huobi Pool Token');
INSERT INTO currencies (name, ticker, description) VALUES ('CryptalDash', 'CRD', 'CryptalDash');
INSERT INTO currencies (name, ticker, description) VALUES ('NULS', 'NULS', 'NULS');
INSERT INTO currencies (name, ticker, description) VALUES ('HyperCash', 'HC', 'HyperCash');
INSERT INTO currencies (name, ticker, description) VALUES ('Kleros', 'PNK', 'Kleros');
INSERT INTO currencies (name, ticker, description) VALUES ('ChainX', 'PCX', 'ChainX');
INSERT INTO currencies (name, ticker, description) VALUES ('Stakenet', 'XSN', 'Stakenet');
INSERT INTO currencies (name, ticker, description) VALUES ('Waves Enterprise', 'WEST', 'Waves Enterprise');
INSERT INTO currencies (name, ticker, description) VALUES ('yOUcash', 'YOUC', 'yOUcash');
INSERT INTO currencies (name, ticker, description) VALUES ('ShareToken', 'SHR', 'ShareToken');
INSERT INTO currencies (name, ticker, description) VALUES ('The Midas Touch Gold', 'TMTG', 'The Midas Touch Gold');
INSERT INTO currencies (name, ticker, description) VALUES ('OctoFi', 'OCTO', 'OctoFi');
INSERT INTO currencies (name, ticker, description) VALUES ('88mph', 'MPH', '88mph');
INSERT INTO currencies (name, ticker, description) VALUES ('MCO', 'MCO', 'MCO');
INSERT INTO currencies (name, ticker, description) VALUES ('Phala.Network', 'PHA', 'Phala.Network');
INSERT INTO currencies (name, ticker, description) VALUES ('COVER Protocol', 'COVER', 'COVER Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Beam', 'BEAM', 'Beam');
INSERT INTO currencies (name, ticker, description) VALUES ('Metal', 'MTL', 'Metal');
INSERT INTO currencies (name, ticker, description) VALUES ('Centrality', 'CENNZ', 'Centrality');
INSERT INTO currencies (name, ticker, description) VALUES ('Waltonchain', 'WTC', 'Waltonchain');
INSERT INTO currencies (name, ticker, description) VALUES ('WazirX', 'WRX', 'WazirX');
INSERT INTO currencies (name, ticker, description) VALUES ('SOLVE', 'SOLVE', 'SOLVE');
INSERT INTO currencies (name, ticker, description) VALUES ('Audius', 'AUDIO', 'Audius');
INSERT INTO currencies (name, ticker, description) VALUES ('RAMP', 'RAMP', 'RAMP');
INSERT INTO currencies (name, ticker, description) VALUES ('Duck DAO (DLP Duck Token)', 'DUCK', 'Duck DAO (DLP Duck Token)');
INSERT INTO currencies (name, ticker, description) VALUES ('Burger Swap', 'BURGER', 'Burger Swap');
INSERT INTO currencies (name, ticker, description) VALUES ('Darwinia Network', 'RING', 'Darwinia Network');
INSERT INTO currencies (name, ticker, description) VALUES ('STEM CELL COIN', 'SCC', 'STEM CELL COIN');
INSERT INTO currencies (name, ticker, description) VALUES ('v.systems', 'VSYS', 'v.systems');
INSERT INTO currencies (name, ticker, description) VALUES ('Bounce Token', 'BOT', 'Bounce Token');
INSERT INTO currencies (name, ticker, description) VALUES ('MAPS', 'MAPS', 'MAPS');
INSERT INTO currencies (name, ticker, description) VALUES ('MANTRA DAO', 'OM', 'MANTRA DAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Bithao', 'BHAO', 'Bithao');
INSERT INTO currencies (name, ticker, description) VALUES ('Bao Finance', 'BAO', 'Bao Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Nexus', 'NXS', 'Nexus');
INSERT INTO currencies (name, ticker, description) VALUES ('0Chain', 'ZCN', '0Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('mStable USD', 'MUSD', 'mStable USD');
INSERT INTO currencies (name, ticker, description) VALUES ('Marlin', 'POND', 'Marlin');
INSERT INTO currencies (name, ticker, description) VALUES ('DigixDAO', 'DGD', 'DigixDAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Nimiq', 'NIM', 'Nimiq');
INSERT INTO currencies (name, ticker, description) VALUES ('Aeternity', 'AE', 'Aeternity');
INSERT INTO currencies (name, ticker, description) VALUES ('Homeros', 'HMR', 'Homeros');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitball Treasure', 'BTRS', 'Bitball Treasure');
INSERT INTO currencies (name, ticker, description) VALUES ('TitanSwap', 'TITAN', 'TitanSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Rubic', 'RBC', 'Rubic');
INSERT INTO currencies (name, ticker, description) VALUES ('Bondly', 'BONDLY', 'Bondly');
INSERT INTO currencies (name, ticker, description) VALUES ('BitcoinPoS', 'BPS', 'BitcoinPoS');
INSERT INTO currencies (name, ticker, description) VALUES ('Orbs', 'ORBS', 'Orbs');
INSERT INTO currencies (name, ticker, description) VALUES ('Orbit Chain', 'ORC', 'Orbit Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('Cindicator', 'CND', 'Cindicator');
INSERT INTO currencies (name, ticker, description) VALUES ('MVL', 'MVL', 'MVL');
INSERT INTO currencies (name, ticker, description) VALUES ('PIVX', 'PIVX', 'PIVX');
INSERT INTO currencies (name, ticker, description) VALUES ('Cortex', 'CTXC', 'Cortex');
INSERT INTO currencies (name, ticker, description) VALUES ('Ignis', 'IGNIS', 'Ignis');
INSERT INTO currencies (name, ticker, description) VALUES ('IDEX', 'IDEX', 'IDEX');
INSERT INTO currencies (name, ticker, description) VALUES ('Dusk Network', 'DUSK', 'Dusk Network');
INSERT INTO currencies (name, ticker, description) VALUES ('USDX [Kava]', 'USDX', 'USDX [Kava]');
INSERT INTO currencies (name, ticker, description) VALUES ('Ripio Credit Network', 'RCN', 'Ripio Credit Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Groestlcoin', 'GRS', 'Groestlcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Measurable Data Token', 'MDT', 'Measurable Data Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Fusion', 'FSN', 'Fusion');
INSERT INTO currencies (name, ticker, description) VALUES ('DAD', 'DAD', 'DAD');
INSERT INTO currencies (name, ticker, description) VALUES ('Contentos', 'COS', 'Contentos');
INSERT INTO currencies (name, ticker, description) VALUES ('Veritaseum', 'VERI', 'Veritaseum');
INSERT INTO currencies (name, ticker, description) VALUES ('Oxen', 'LOKI', 'Oxen');
INSERT INTO currencies (name, ticker, description) VALUES ('inSure DeFi', 'SURE', 'inSure DeFi');
INSERT INTO currencies (name, ticker, description) VALUES ('TerraKRW', 'KRT', 'TerraKRW');
INSERT INTO currencies (name, ticker, description) VALUES ('Prometeus', 'PROM', 'Prometeus');
INSERT INTO currencies (name, ticker, description) VALUES ('Pickle Finance', 'PICKLE', 'Pickle Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Shopping', 'SPI', 'Shopping');
INSERT INTO currencies (name, ticker, description) VALUES ('JulSwap', 'JULD', 'JulSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Frax Share', 'FXS', 'Frax Share');
INSERT INTO currencies (name, ticker, description) VALUES ('ARPA Chain', 'ARPA', 'ARPA Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('Whiteheart', 'WHITE', 'Whiteheart');
INSERT INTO currencies (name, ticker, description) VALUES ('Bankera', 'BNK', 'Bankera');
INSERT INTO currencies (name, ticker, description) VALUES ('Cartesi', 'CTSI', 'Cartesi');
INSERT INTO currencies (name, ticker, description) VALUES ('Celo Dollar', 'CUSD', 'Celo Dollar');
INSERT INTO currencies (name, ticker, description) VALUES ('AirSwap', 'AST', 'AirSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Thunder Token', 'TT', 'Thunder Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Neutrino Token', 'NSBT', 'Neutrino Token');
INSERT INTO currencies (name, ticker, description) VALUES ('BOSAGORA', 'BOA', 'BOSAGORA');
INSERT INTO currencies (name, ticker, description) VALUES ('GXChain', 'GXC', 'GXChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Decentr', 'DEC', 'Decentr');
INSERT INTO currencies (name, ticker, description) VALUES ('LGCY Network', 'LGCY', 'LGCY Network');
INSERT INTO currencies (name, ticker, description) VALUES ('BoringDAO', 'BOR', 'BoringDAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Lambda', 'LAMB', 'Lambda');
INSERT INTO currencies (name, ticker, description) VALUES ('Super Zero Protocol', 'SERO', 'Super Zero Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Klever', 'KLV', 'Klever');
INSERT INTO currencies (name, ticker, description) VALUES ('Quantstamp', 'QSP', 'Quantstamp');
INSERT INTO currencies (name, ticker, description) VALUES ('Switcheo', 'SWTH', 'Switcheo');
INSERT INTO currencies (name, ticker, description) VALUES ('Kadena', 'KDA', 'Kadena');
INSERT INTO currencies (name, ticker, description) VALUES ('Neblio', 'NEBL', 'Neblio');
INSERT INTO currencies (name, ticker, description) VALUES ('Ducato Protocol Token', 'DUCATO', 'Ducato Protocol Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Gas', 'GAS', 'Gas');
INSERT INTO currencies (name, ticker, description) VALUES ('1irstcoin', 'FST', '1irstcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Zap', 'ZAP', 'Zap');
INSERT INTO currencies (name, ticker, description) VALUES ('Wirex Token', 'WXT', 'Wirex Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus USDT', 'vUSDT', 'Venus USDT');
INSERT INTO currencies (name, ticker, description) VALUES ('Hermez Network', 'HEZ', 'Hermez Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Grin', 'GRIN', 'Grin');
INSERT INTO currencies (name, ticker, description) VALUES ('Ultiledger', 'ULT', 'Ultiledger');
INSERT INTO currencies (name, ticker, description) VALUES ('Perlin', 'PERL', 'Perlin');
INSERT INTO currencies (name, ticker, description) VALUES ('Aleph.im', 'ALEPH', 'Aleph.im');
INSERT INTO currencies (name, ticker, description) VALUES ('DEXTools', 'DEXT', 'DEXTools');
INSERT INTO currencies (name, ticker, description) VALUES ('SALT', 'SALT', 'SALT');
INSERT INTO currencies (name, ticker, description) VALUES ('Tixl [NEW]', 'TXL', 'Tixl [NEW]');
INSERT INTO currencies (name, ticker, description) VALUES ('Metronome', 'MET', 'Metronome');
INSERT INTO currencies (name, ticker, description) VALUES ('Basis Cash', 'BAC', 'Basis Cash');
INSERT INTO currencies (name, ticker, description) VALUES ('Presearch', 'PRE', 'Presearch');
INSERT INTO currencies (name, ticker, description) VALUES ('dForce', 'DF', 'dForce');
INSERT INTO currencies (name, ticker, description) VALUES ('Wing', 'WING', 'Wing');
INSERT INTO currencies (name, ticker, description) VALUES ('Robonomics.network', 'XRT', 'Robonomics.network');
INSERT INTO currencies (name, ticker, description) VALUES ('USDK', 'USDK', 'USDK');
INSERT INTO currencies (name, ticker, description) VALUES ('Sentivate', 'SNTVT', 'Sentivate');
INSERT INTO currencies (name, ticker, description) VALUES ('Nexalt', 'XLT', 'Nexalt');
INSERT INTO currencies (name, ticker, description) VALUES ('Pirate Chain', 'ARRR', 'Pirate Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('BORA', 'BORA', 'BORA');
INSERT INTO currencies (name, ticker, description) VALUES ('NKN', 'NKN', 'NKN');
INSERT INTO currencies (name, ticker, description) VALUES ('Benchmark Protocol', 'MARK', 'Benchmark Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Gleec', 'GLEEC', 'Gleec');
INSERT INTO currencies (name, ticker, description) VALUES ('Decentralized Vulnerability Platform', 'DVP', 'Decentralized Vulnerability Platform');
INSERT INTO currencies (name, ticker, description) VALUES ('FIO Protocol', 'FIO', 'FIO Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Cocos-BCX', 'COCOS', 'Cocos-BCX');
INSERT INTO currencies (name, ticker, description) VALUES ('RSK Smart Bitcoin', 'RBTC', 'RSK Smart Bitcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Tixl [old]', 'MTXLT', 'Tixl [old]');
INSERT INTO currencies (name, ticker, description) VALUES ('OptionRoom', 'ROOM', 'OptionRoom');
INSERT INTO currencies (name, ticker, description) VALUES ('Frontier', 'FRONT', 'Frontier');
INSERT INTO currencies (name, ticker, description) VALUES ('Carry', 'CRE', 'Carry');
INSERT INTO currencies (name, ticker, description) VALUES ('PEAKDEFI', 'PEAK', 'PEAKDEFI');
INSERT INTO currencies (name, ticker, description) VALUES ('Metaverse Dualchain Network Architecture', 'DNA', 'Metaverse Dualchain Network Architecture');
INSERT INTO currencies (name, ticker, description) VALUES ('VerusCoin', 'VRSC', 'VerusCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Nebulas', 'NAS', 'Nebulas');
INSERT INTO currencies (name, ticker, description) VALUES ('EasyFi', 'EASY', 'EasyFi');
INSERT INTO currencies (name, ticker, description) VALUES ('Nash Exchange', 'NEX', 'Nash Exchange');
INSERT INTO currencies (name, ticker, description) VALUES ('dHedge DAO', 'DHT', 'dHedge DAO');
INSERT INTO currencies (name, ticker, description) VALUES ('BnkToTheFuture', 'BFT', 'BnkToTheFuture');
INSERT INTO currencies (name, ticker, description) VALUES ('Einsteinium', 'EMC2', 'Einsteinium');
INSERT INTO currencies (name, ticker, description) VALUES ('Quantum Resistant Ledger', 'QRL', 'Quantum Resistant Ledger');
INSERT INTO currencies (name, ticker, description) VALUES ('DREP', 'DREP', 'DREP');
INSERT INTO currencies (name, ticker, description) VALUES ('Bonfida', 'FIDA', 'Bonfida');
INSERT INTO currencies (name, ticker, description) VALUES ('VIDT Datalink', 'VIDT', 'VIDT Datalink');
INSERT INTO currencies (name, ticker, description) VALUES ('Safex Token', 'SFT', 'Safex Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Navcoin', 'NAV', 'Navcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Standard Tokenization Protocol', 'STPT', 'Standard Tokenization Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('12Ships', 'TSHP', '12Ships');
INSERT INTO currencies (name, ticker, description) VALUES ('Propy', 'PRO', 'Propy');
INSERT INTO currencies (name, ticker, description) VALUES ('BASIC', 'BASIC', 'BASIC');
INSERT INTO currencies (name, ticker, description) VALUES ('Leverj Gluon', 'L2', 'Leverj Gluon');
INSERT INTO currencies (name, ticker, description) VALUES ('Proton', 'XPR', 'Proton');
INSERT INTO currencies (name, ticker, description) VALUES ('Steem Dollars', 'SBD', 'Steem Dollars');
INSERT INTO currencies (name, ticker, description) VALUES ('Counos Coin', 'CCA', 'Counos Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Chromia', 'CHR', 'Chromia');
INSERT INTO currencies (name, ticker, description) VALUES ('SnowSwap', 'SNOW', 'SnowSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Constellation', 'DAG', 'Constellation');
INSERT INTO currencies (name, ticker, description) VALUES ('Function X', 'FX', 'Function X');
INSERT INTO currencies (name, ticker, description) VALUES ('Obyte', 'GBYTE', 'Obyte');
INSERT INTO currencies (name, ticker, description) VALUES ('GoChain', 'GO', 'GoChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Xensor', 'XSR', 'Xensor');
INSERT INTO currencies (name, ticker, description) VALUES ('Telos', 'TLOS', 'Telos');
INSERT INTO currencies (name, ticker, description) VALUES ('Refereum', 'RFR', 'Refereum');
INSERT INTO currencies (name, ticker, description) VALUES ('Meme', 'MEME', 'Meme');
INSERT INTO currencies (name, ticker, description) VALUES ('PRIZM', 'PZM', 'PRIZM');
INSERT INTO currencies (name, ticker, description) VALUES ('Nxt', 'NXT', 'Nxt');
INSERT INTO currencies (name, ticker, description) VALUES ('Spendcoin', 'SPND', 'Spendcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('ASTA', 'ASTA', 'ASTA');
INSERT INTO currencies (name, ticker, description) VALUES ('Phoenix Global', 'PHB', 'Phoenix Global');
INSERT INTO currencies (name, ticker, description) VALUES ('Furucombo', 'COMBO', 'Furucombo');
INSERT INTO currencies (name, ticker, description) VALUES ('Render Token', 'RNDR', 'Render Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Aavegotchi', 'GHST', 'Aavegotchi');
INSERT INTO currencies (name, ticker, description) VALUES ('Skycoin', 'SKY', 'Skycoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Vertcoin', 'VTC', 'Vertcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('APY.Finance', 'APY', 'APY.Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Rio DeFi', 'RFUEL', 'Rio DeFi');
INSERT INTO currencies (name, ticker, description) VALUES ('BitcoinHD', 'BHD', 'BitcoinHD');
INSERT INTO currencies (name, ticker, description) VALUES ('Anyswap', 'ANY', 'Anyswap');
INSERT INTO currencies (name, ticker, description) VALUES ('Multiplier', 'MXX', 'Multiplier');
INSERT INTO currencies (name, ticker, description) VALUES ('StableXSwap', 'STAX', 'StableXSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Swingby', 'SWINGBY', 'Swingby');
INSERT INTO currencies (name, ticker, description) VALUES ('RChain', 'REV', 'RChain');
INSERT INTO currencies (name, ticker, description) VALUES ('NerveNetwork', 'NVT', 'NerveNetwork');
INSERT INTO currencies (name, ticker, description) VALUES ('SpaceChain', 'SPC', 'SpaceChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Swerve', 'SWRV', 'Swerve');
INSERT INTO currencies (name, ticker, description) VALUES ('Lido DAO Token', 'LDO', 'Lido DAO Token');
INSERT INTO currencies (name, ticker, description) VALUES ('WOM Protocol', 'WOM', 'WOM Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('VITE', 'VITE', 'VITE');
INSERT INTO currencies (name, ticker, description) VALUES ('Crypterium', 'CRPT', 'Crypterium');
INSERT INTO currencies (name, ticker, description) VALUES ('Global Digital Content', 'GDC', 'Global Digital Content');
INSERT INTO currencies (name, ticker, description) VALUES ('Oraichain Token', 'ORAI', 'Oraichain Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Factom', 'FCT', 'Factom');
INSERT INTO currencies (name, ticker, description) VALUES ('QASH', 'QASH', 'QASH');
INSERT INTO currencies (name, ticker, description) VALUES ('Aurora', 'AOA', 'Aurora');
INSERT INTO currencies (name, ticker, description) VALUES ('Selfkey', 'KEY', 'Selfkey');
INSERT INTO currencies (name, ticker, description) VALUES ('KeeperDAO', 'ROOK', 'KeeperDAO');
INSERT INTO currencies (name, ticker, description) VALUES ('REVV', 'REVV', 'REVV');
INSERT INTO currencies (name, ticker, description) VALUES ('PAC Global', 'PAC', 'PAC Global');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus SXP', 'vSXP', 'Venus SXP');
INSERT INTO currencies (name, ticker, description) VALUES ('ForTube', 'FOR', 'ForTube');
INSERT INTO currencies (name, ticker, description) VALUES ('Namecoin', 'NMC', 'Namecoin');
INSERT INTO currencies (name, ticker, description) VALUES ('AppCoins', 'APPC', 'AppCoins');
INSERT INTO currencies (name, ticker, description) VALUES ('Anchor Neural World', 'ANW', 'Anchor Neural World');
INSERT INTO currencies (name, ticker, description) VALUES ('YF Link', 'YFL', 'YF Link');
INSERT INTO currencies (name, ticker, description) VALUES ('Raiden Network Token', 'RDN', 'Raiden Network Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Wootrade', 'WOO', 'Wootrade');
INSERT INTO currencies (name, ticker, description) VALUES ('Aergo', 'AERGO', 'Aergo');
INSERT INTO currencies (name, ticker, description) VALUES ('FC Barcelona Fan Token', 'BAR', 'FC Barcelona Fan Token');
INSERT INTO currencies (name, ticker, description) VALUES ('ZEON', 'ZEON', 'ZEON');
INSERT INTO currencies (name, ticker, description) VALUES ('Galatasaray Fan Token', 'GAL', 'Galatasaray Fan Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Zynecoin', 'ZYN', 'Zynecoin');
INSERT INTO currencies (name, ticker, description) VALUES ('JustLiquidity', 'JUL', 'JustLiquidity');
INSERT INTO currencies (name, ticker, description) VALUES ('UniLend', 'UFT', 'UniLend');
INSERT INTO currencies (name, ticker, description) VALUES ('YFDAI.FINANCE', 'YF-DAI', 'YFDAI.FINANCE');
INSERT INTO currencies (name, ticker, description) VALUES ('Moeda Loyalty Points', 'MDA', 'Moeda Loyalty Points');
INSERT INTO currencies (name, ticker, description) VALUES ('Hacken Token', 'HAI', 'Hacken Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Viacoin', 'VIA', 'Viacoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Rally', 'RLY', 'Rally');
INSERT INTO currencies (name, ticker, description) VALUES ('BitKan', 'KAN', 'BitKan');
INSERT INTO currencies (name, ticker, description) VALUES ('Poolz Finance', 'POOLZ', 'Poolz Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('SUKU', 'SUKU', 'SUKU');
INSERT INTO currencies (name, ticker, description) VALUES ('ARMOR', 'ARMOR', 'ARMOR');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus LINK', 'vLINK', 'Venus LINK');
INSERT INTO currencies (name, ticker, description) VALUES ('Dynamic Trading Rights', 'DTR', 'Dynamic Trading Rights');
INSERT INTO currencies (name, ticker, description) VALUES ('Dock', 'DOCK', 'Dock');
INSERT INTO currencies (name, ticker, description) VALUES ('DigitalBits', 'XDB', 'DigitalBits');
INSERT INTO currencies (name, ticker, description) VALUES ('Endor Protocol', 'EDR', 'Endor Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('SIRIN LABS Token', 'SRN', 'SIRIN LABS Token');
INSERT INTO currencies (name, ticker, description) VALUES ('GeoDB', 'GEO', 'GeoDB');
INSERT INTO currencies (name, ticker, description) VALUES ('Props Token', 'PROPS', 'Props Token');
INSERT INTO currencies (name, ticker, description) VALUES ('DMarket', 'DMT', 'DMarket');
INSERT INTO currencies (name, ticker, description) VALUES ('OAX', 'OAX', 'OAX');
INSERT INTO currencies (name, ticker, description) VALUES ('BigONE Token', 'ONE', 'BigONE Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Mithril', 'MITH', 'Mithril');
INSERT INTO currencies (name, ticker, description) VALUES ('Bifrost', 'BFC', 'Bifrost');
INSERT INTO currencies (name, ticker, description) VALUES ('TrueChain', 'ИСТИНА', 'TrueChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Invictus Hyperion Fund', 'IHF', 'Invictus Hyperion Fund');
INSERT INTO currencies (name, ticker, description) VALUES ('Decentral Games', 'DG', 'Decentral Games');
INSERT INTO currencies (name, ticker, description) VALUES ('Crust', 'CRU', 'Crust');
INSERT INTO currencies (name, ticker, description) VALUES ('Morpheus Labs', 'MITX', 'Morpheus Labs');
INSERT INTO currencies (name, ticker, description) VALUES ('Arcblock', 'ABT', 'Arcblock');
INSERT INTO currencies (name, ticker, description) VALUES ('Project Pai', 'PAI', 'Project Pai');
INSERT INTO currencies (name, ticker, description) VALUES ('Gifto', 'GTO', 'Gifto');
INSERT INTO currencies (name, ticker, description) VALUES ('LGO Token', 'LGO', 'LGO Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Metaverse ETP', 'ETP', 'Metaverse ETP');
INSERT INTO currencies (name, ticker, description) VALUES ('King DAG', 'KDAG', 'King DAG');
INSERT INTO currencies (name, ticker, description) VALUES ('Hashgard', 'GARD', 'Hashgard');
INSERT INTO currencies (name, ticker, description) VALUES ('suterusu', 'SUTER', 'suterusu');
INSERT INTO currencies (name, ticker, description) VALUES ('Newscrypto', 'NWC', 'Newscrypto');
INSERT INTO currencies (name, ticker, description) VALUES ('Wabi', 'WABI', 'Wabi');
INSERT INTO currencies (name, ticker, description) VALUES ('USDJ', 'USDJ', 'USDJ');
INSERT INTO currencies (name, ticker, description) VALUES ('reflect.finance', 'RFI', 'reflect.finance');
INSERT INTO currencies (name, ticker, description) VALUES ('KLAYswap Protocol', 'KSP', 'KLAYswap Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Sentinel Protocol', 'UPP', 'Sentinel Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Genesis Vision', 'GVT', 'Genesis Vision');
INSERT INTO currencies (name, ticker, description) VALUES ('YIELD App', 'YLD', 'YIELD App');
INSERT INTO currencies (name, ticker, description) VALUES ('PlatonCoin', 'PLTC', 'PlatonCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Atomic Wallet Coin', 'AWC', 'Atomic Wallet Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Davinci Coin', 'DAC', 'Davinci Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('MediBloc', 'MED', 'MediBloc');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus LTC', 'vLTC', 'Venus LTC');
INSERT INTO currencies (name, ticker, description) VALUES ('Apollo Currency', 'APL', 'Apollo Currency');
INSERT INTO currencies (name, ticker, description) VALUES ('TenX', 'PAY', 'TenX');
INSERT INTO currencies (name, ticker, description) VALUES ('Molecular Future', 'MOF', 'Molecular Future');
INSERT INTO currencies (name, ticker, description) VALUES ('QLC Chain', 'QLC', 'QLC Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('AMO Coin', 'AMO', 'AMO Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Universa', 'UTNP', 'Universa');
INSERT INTO currencies (name, ticker, description) VALUES ('LATOKEN', 'LA', 'LATOKEN');
INSERT INTO currencies (name, ticker, description) VALUES ('Idle', 'IDLE', 'Idle');
INSERT INTO currencies (name, ticker, description) VALUES ('VestChain', 'VEST', 'VestChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Stafi', 'FIS', 'Stafi');
INSERT INTO currencies (name, ticker, description) VALUES ('Beowulf', 'BWF', 'Beowulf');
INSERT INTO currencies (name, ticker, description) VALUES ('Bread', 'BRD', 'Bread');
INSERT INTO currencies (name, ticker, description) VALUES ('Ambrosus', 'AMB', 'Ambrosus');
INSERT INTO currencies (name, ticker, description) VALUES ('VideoCoin', 'VID', 'VideoCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('S4FE', 'S4F', 'S4FE');
INSERT INTO currencies (name, ticker, description) VALUES ('PLATINCOIN', 'PLC', 'PLATINCOIN');
INSERT INTO currencies (name, ticker, description) VALUES ('BIKI', 'BIKI', 'BIKI');
INSERT INTO currencies (name, ticker, description) VALUES ('Gem Exchange And Trading', 'GXT', 'Gem Exchange And Trading');
INSERT INTO currencies (name, ticker, description) VALUES ('BitForex Token', 'BF', 'BitForex Token');
INSERT INTO currencies (name, ticker, description) VALUES ('MovieBloc', 'MBL', 'MovieBloc');
INSERT INTO currencies (name, ticker, description) VALUES ('DOS Network', 'DOS', 'DOS Network');
INSERT INTO currencies (name, ticker, description) VALUES ('BHPCoin', 'BHP', 'BHPCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('LockTrip', 'LOC', 'LockTrip');
INSERT INTO currencies (name, ticker, description) VALUES ('Base Protocol', 'BASE', 'Base Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('IQeon', 'IQN', 'IQeon');
INSERT INTO currencies (name, ticker, description) VALUES ('ThoreNext', 'THX', 'ThoreNext');
INSERT INTO currencies (name, ticker, description) VALUES ('DSLA Protocol', 'DSLA', 'DSLA Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('OST', 'OST', 'OST');
INSERT INTO currencies (name, ticker, description) VALUES ('Nucleus Vision', 'NCASH', 'Nucleus Vision');
INSERT INTO currencies (name, ticker, description) VALUES ('DeXe', 'DEXE', 'DeXe');
INSERT INTO currencies (name, ticker, description) VALUES ('Dego Finance', 'DEGO', 'Dego Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('Emirex Token', 'EMRX', 'Emirex Token');
INSERT INTO currencies (name, ticker, description) VALUES ('LinkEye', 'LET', 'LinkEye');
INSERT INTO currencies (name, ticker, description) VALUES ('LUKSO', 'LYXe', 'LUKSO');
INSERT INTO currencies (name, ticker, description) VALUES ('MiL.k', 'MLK', 'MiL.k');
INSERT INTO currencies (name, ticker, description) VALUES ('Tachyon Protocol', 'IPX', 'Tachyon Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitcoin 2', 'BTC2', 'Bitcoin 2');
INSERT INTO currencies (name, ticker, description) VALUES ('Humanscape', 'HUM', 'Humanscape');
INSERT INTO currencies (name, ticker, description) VALUES ('Archer DAO Governance Token', 'ARCH', 'Archer DAO Governance Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Kcash', 'KCASH', 'Kcash');
INSERT INTO currencies (name, ticker, description) VALUES ('Santiment Network Token', 'SAN', 'Santiment Network Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Peercoin', 'PPC', 'Peercoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Moss Coin', 'MOC', 'Moss Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('AnimalGo', 'GOM2', 'AnimalGo');
INSERT INTO currencies (name, ticker, description) VALUES ('Maro', 'MARO', 'Maro');
INSERT INTO currencies (name, ticker, description) VALUES ('PowerTrade Fuel', 'PTF', 'PowerTrade Fuel');
INSERT INTO currencies (name, ticker, description) VALUES ('Ruff', 'RUFF', 'Ruff');
INSERT INTO currencies (name, ticker, description) VALUES ('Indexed Finance', 'NDX', 'Indexed Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('TokenClub', 'TCT', 'TokenClub');
INSERT INTO currencies (name, ticker, description) VALUES ('Metadium', 'META', 'Metadium');
INSERT INTO currencies (name, ticker, description) VALUES ('dKargo', 'DKA', 'dKargo');
INSERT INTO currencies (name, ticker, description) VALUES ('Dynamic', 'DYN', 'Dynamic');
INSERT INTO currencies (name, ticker, description) VALUES ('Juventus Fan Token', 'JUV', 'Juventus Fan Token');
INSERT INTO currencies (name, ticker, description) VALUES ('NEXT', 'NET', 'NEXT');
INSERT INTO currencies (name, ticker, description) VALUES ('Monolith', 'TKN', 'Monolith');
INSERT INTO currencies (name, ticker, description) VALUES ('Ubiq', 'UBQ', 'Ubiq');
INSERT INTO currencies (name, ticker, description) VALUES ('Paris Saint-Germain Fan Token', 'PSG', 'Paris Saint-Germain Fan Token');
INSERT INTO currencies (name, ticker, description) VALUES ('PumaPay', 'PMA', 'PumaPay');
INSERT INTO currencies (name, ticker, description) VALUES ('SmartCash', 'SMART', 'SmartCash');
INSERT INTO currencies (name, ticker, description) VALUES ('ZeroSwap', 'ZEE', 'ZeroSwap');
INSERT INTO currencies (name, ticker, description) VALUES ('Dero', 'DERO', 'Dero');
INSERT INTO currencies (name, ticker, description) VALUES ('PieDAO DOUGH v2', 'DOUGH', 'PieDAO DOUGH v2');
INSERT INTO currencies (name, ticker, description) VALUES ('Everex', 'EVX', 'Everex');
INSERT INTO currencies (name, ticker, description) VALUES ('CONUN', 'CON', 'CONUN');
INSERT INTO currencies (name, ticker, description) VALUES ('#MetaHash', 'MHC', '#MetaHash');
INSERT INTO currencies (name, ticker, description) VALUES ('NIX', 'NIX', 'NIX');
INSERT INTO currencies (name, ticker, description) VALUES ('LCX', 'LCX', 'LCX');
INSERT INTO currencies (name, ticker, description) VALUES ('CoinEx Token', 'CET', 'CoinEx Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Yield Optimization Platform & Protocol', 'YOP', 'Yield Optimization Platform & Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('DigitalNote', 'XDN', 'DigitalNote');
INSERT INTO currencies (name, ticker, description) VALUES ('Blox', 'CDT', 'Blox');
INSERT INTO currencies (name, ticker, description) VALUES ('Tap', 'XTP', 'Tap');
INSERT INTO currencies (name, ticker, description) VALUES ('LiquidApps', 'DAPP', 'LiquidApps');
INSERT INTO currencies (name, ticker, description) VALUES ('Bit-Z Token', 'BZ', 'Bit-Z Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Sentinel', 'SENT', 'Sentinel');
INSERT INTO currencies (name, ticker, description) VALUES ('Levolution', 'LEVL', 'Levolution');
INSERT INTO currencies (name, ticker, description) VALUES ('Veros', 'VRS', 'Veros');
INSERT INTO currencies (name, ticker, description) VALUES ('Alchemy Pay', 'ACH', 'Alchemy Pay');
INSERT INTO currencies (name, ticker, description) VALUES ('StakeCubeCoin', 'SCC', 'StakeCubeCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('PCHAIN', 'PI', 'PCHAIN');
INSERT INTO currencies (name, ticker, description) VALUES ('HUNT', 'HUNT', 'HUNT');
INSERT INTO currencies (name, ticker, description) VALUES ('Tokenomy', 'TEN', 'Tokenomy');
INSERT INTO currencies (name, ticker, description) VALUES ('CyberMiles', 'CMT', 'CyberMiles');
INSERT INTO currencies (name, ticker, description) VALUES ('Aryacoin', 'AYA', 'Aryacoin');
INSERT INTO currencies (name, ticker, description) VALUES ('WePower', 'WPR', 'WePower');
INSERT INTO currencies (name, ticker, description) VALUES ('smARTOFGIVING', 'AOG', 'smARTOFGIVING');
INSERT INTO currencies (name, ticker, description) VALUES ('ZBG Token', 'ZT', 'ZBG Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Smart MFG', 'MFG', 'Smart MFG');
INSERT INTO currencies (name, ticker, description) VALUES ('Trittium', 'TRTT', 'Trittium');
INSERT INTO currencies (name, ticker, description) VALUES ('CUTcoin', 'CUT', 'CUTcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Hakka.Finance', 'HAKKA', 'Hakka.Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('High Performance Blockchain', 'HPB', 'High Performance Blockchain');
INSERT INTO currencies (name, ticker, description) VALUES ('POA', 'POA', 'POA');
INSERT INTO currencies (name, ticker, description) VALUES ('Anchor', 'ANCT', 'Anchor');
INSERT INTO currencies (name, ticker, description) VALUES ('CUDOS', 'CUDOS', 'CUDOS');
INSERT INTO currencies (name, ticker, description) VALUES ('Gulden', 'NLG', 'Gulden');
INSERT INTO currencies (name, ticker, description) VALUES ('Particl', 'PART', 'Particl');
INSERT INTO currencies (name, ticker, description) VALUES ('Blocknet', 'BLOCK', 'Blocknet');
INSERT INTO currencies (name, ticker, description) VALUES ('Content Value Network', 'CVNT', 'Content Value Network');
INSERT INTO currencies (name, ticker, description) VALUES ('VIDY', 'VIDY', 'VIDY');
INSERT INTO currencies (name, ticker, description) VALUES ('LikeCoin', 'LIKE', 'LikeCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Observer', 'OBSR', 'Observer');
INSERT INTO currencies (name, ticker, description) VALUES ('Stake DAO', 'SDT', 'Stake DAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Time New Bank', 'TNB', 'Time New Bank');
INSERT INTO currencies (name, ticker, description) VALUES ('carVertical', 'CV', 'carVertical');
INSERT INTO currencies (name, ticker, description) VALUES ('AGA Token', 'AGA', 'AGA Token');
INSERT INTO currencies (name, ticker, description) VALUES ('TE-FOOD', 'TONE', 'TE-FOOD');
INSERT INTO currencies (name, ticker, description) VALUES ('DeFi Yield Protocol', 'DYP', 'DeFi Yield Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Prosper', 'PROS', 'Prosper');
INSERT INTO currencies (name, ticker, description) VALUES ('Validity', 'VAL', 'Validity');
INSERT INTO currencies (name, ticker, description) VALUES ('Geeq', 'GEEQ', 'Geeq');
INSERT INTO currencies (name, ticker, description) VALUES ('MahaDAO', 'MAHA', 'MahaDAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Achain', 'ACT', 'Achain');
INSERT INTO currencies (name, ticker, description) VALUES ('DATA', 'DTA', 'DATA');
INSERT INTO currencies (name, ticker, description) VALUES ('Blockzero Labs', 'XIO', 'Blockzero Labs');
INSERT INTO currencies (name, ticker, description) VALUES ('SymVerse', 'SYM', 'SymVerse');
INSERT INTO currencies (name, ticker, description) VALUES ('Newton', 'NEW', 'Newton');
INSERT INTO currencies (name, ticker, description) VALUES ('FirmaChain', 'FCT', 'FirmaChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Mettalex', 'MTLX', 'Mettalex');
INSERT INTO currencies (name, ticker, description) VALUES ('TOP', 'TOP', 'TOP');
INSERT INTO currencies (name, ticker, description) VALUES ('Unitrade', 'TRADE', 'Unitrade');
INSERT INTO currencies (name, ticker, description) VALUES ('Holyheld', 'HOLY', 'Holyheld');
INSERT INTO currencies (name, ticker, description) VALUES ('MixMarvel', 'MIX', 'MixMarvel');
INSERT INTO currencies (name, ticker, description) VALUES ('Bird.Money', 'BIRD', 'Bird.Money');
INSERT INTO currencies (name, ticker, description) VALUES ('PIXEL', 'PXL', 'PIXEL');
INSERT INTO currencies (name, ticker, description) VALUES ('Phantasma', 'SOUL', 'Phantasma');
INSERT INTO currencies (name, ticker, description) VALUES ('FOAM', 'FOAM', 'FOAM');
INSERT INTO currencies (name, ticker, description) VALUES ('Dawn Protocol', 'DAWN', 'Dawn Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Agrello', 'DLT', 'Agrello');
INSERT INTO currencies (name, ticker, description) VALUES ('Tokamak Network', 'TON', 'Tokamak Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Auctus', 'AUC', 'Auctus');
INSERT INTO currencies (name, ticker, description) VALUES ('TrustVerse', 'TRV', 'TrustVerse');
INSERT INTO currencies (name, ticker, description) VALUES ('OpenDAO', 'OPEN', 'OpenDAO');
INSERT INTO currencies (name, ticker, description) VALUES ('Bibox Token', 'BIX', 'Bibox Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Hedget', 'HGET', 'Hedget');
INSERT INTO currencies (name, ticker, description) VALUES ('Casino Betting Coin', 'CBC', 'Casino Betting Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Crowns', 'CWS', 'Crowns');
INSERT INTO currencies (name, ticker, description) VALUES ('CanYaCoin', 'CAN', 'CanYaCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Mysterium', 'MYST', 'Mysterium');
INSERT INTO currencies (name, ticker, description) VALUES ('Nestree', 'EGG', 'Nestree');
INSERT INTO currencies (name, ticker, description) VALUES ('YOYOW', 'YOYOW', 'YOYOW');
INSERT INTO currencies (name, ticker, description) VALUES ('STATERA', 'STA', 'STATERA');
INSERT INTO currencies (name, ticker, description) VALUES ('Rarible', 'RARI', 'Rarible');
INSERT INTO currencies (name, ticker, description) VALUES ('Effect.AI', 'EFX', 'Effect.AI');
INSERT INTO currencies (name, ticker, description) VALUES ('Lamden', 'TAU', 'Lamden');
INSERT INTO currencies (name, ticker, description) VALUES ('Quiztok', 'QTCON', 'Quiztok');
INSERT INTO currencies (name, ticker, description) VALUES ('Opacity', 'OPCT', 'Opacity');
INSERT INTO currencies (name, ticker, description) VALUES ('RING X PLATFORM', 'RINGX', 'RING X PLATFORM');
INSERT INTO currencies (name, ticker, description) VALUES ('Viberate', 'VIB', 'Viberate');
INSERT INTO currencies (name, ticker, description) VALUES ('Wagerr', 'WGR', 'Wagerr');
INSERT INTO currencies (name, ticker, description) VALUES ('SwftCoin', 'SWFTC', 'SwftCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('ROOBEE', 'ROOBEE', 'ROOBEE');
INSERT INTO currencies (name, ticker, description) VALUES ('DEX', 'DEX', 'DEX');
INSERT INTO currencies (name, ticker, description) VALUES ('Metrix Coin', 'MRX', 'Metrix Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Mooncoin', 'MOON', 'Mooncoin');
INSERT INTO currencies (name, ticker, description) VALUES ('EUNO', 'EUNO', 'EUNO');
INSERT INTO currencies (name, ticker, description) VALUES ('Filecash', 'FIC', 'Filecash');
INSERT INTO currencies (name, ticker, description) VALUES ('GameCredits', 'GAME', 'GameCredits');
INSERT INTO currencies (name, ticker, description) VALUES ('SaTT', 'SATT', 'SaTT');
INSERT INTO currencies (name, ticker, description) VALUES ('Aitra', 'AITRA', 'Aitra');
INSERT INTO currencies (name, ticker, description) VALUES ('Feathercoin', 'FTC', 'Feathercoin');
INSERT INTO currencies (name, ticker, description) VALUES ('GET Protocol', 'GET', 'GET Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Kryll', 'KRL', 'Kryll');
INSERT INTO currencies (name, ticker, description) VALUES ('Elamachain', 'ELAMA', 'Elamachain');
INSERT INTO currencies (name, ticker, description) VALUES ('Realio Network', 'RIO', 'Realio Network');
INSERT INTO currencies (name, ticker, description) VALUES ('APIX', 'APIX', 'APIX');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus DOT', 'vDOT', 'Venus DOT');
INSERT INTO currencies (name, ticker, description) VALUES ('FIBOS', 'FO', 'FIBOS');
INSERT INTO currencies (name, ticker, description) VALUES ('Burst', 'BURST', 'Burst');
INSERT INTO currencies (name, ticker, description) VALUES ('Bonded Finance', 'BOND', 'Bonded Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('XMax', 'XMX', 'XMax');
INSERT INTO currencies (name, ticker, description) VALUES ('Monetha', 'MTH', 'Monetha');
INSERT INTO currencies (name, ticker, description) VALUES ('Swace', 'SWACE', 'Swace');
INSERT INTO currencies (name, ticker, description) VALUES ('ILCOIN', 'ILC', 'ILCOIN');
INSERT INTO currencies (name, ticker, description) VALUES ('FNB Protocol', 'FNB', 'FNB Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Grid+', 'GRID', 'Grid+');
INSERT INTO currencies (name, ticker, description) VALUES ('Autonio', 'NIOX', 'Autonio');
INSERT INTO currencies (name, ticker, description) VALUES ('X-CASH', 'XCASH', 'X-CASH');
INSERT INTO currencies (name, ticker, description) VALUES ('Digitex Token', 'DGTX', 'Digitex Token');
INSERT INTO currencies (name, ticker, description) VALUES ('CWV Chain', 'CWV', 'CWV Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('Eminer', 'EM', 'Eminer');
INSERT INTO currencies (name, ticker, description) VALUES ('Jibrel Network', 'JNT', 'Jibrel Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Cobak Token', 'CBK', 'Cobak Token');
INSERT INTO currencies (name, ticker, description) VALUES ('UniLayer', 'LAYER', 'UniLayer');
INSERT INTO currencies (name, ticker, description) VALUES ('BLOCKv', 'VEE', 'BLOCKv');
INSERT INTO currencies (name, ticker, description) VALUES ('PotCoin', 'POT', 'PotCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('CargoX', 'CXO', 'CargoX');
INSERT INTO currencies (name, ticker, description) VALUES ('GoCrypto Token', 'GOC', 'GoCrypto Token');
INSERT INTO currencies (name, ticker, description) VALUES ('BIZZCOIN', 'BIZZ', 'BIZZCOIN');
INSERT INTO currencies (name, ticker, description) VALUES ('BTSE', 'BTSE', 'BTSE');
INSERT INTO currencies (name, ticker, description) VALUES ('Polis', 'POLIS', 'Polis');
INSERT INTO currencies (name, ticker, description) VALUES ('Myriad', 'XMY', 'Myriad');
INSERT INTO currencies (name, ticker, description) VALUES ('ASKO', 'ASKO', 'ASKO');
INSERT INTO currencies (name, ticker, description) VALUES ('Seele-N', 'SEELE', 'Seele-N');
INSERT INTO currencies (name, ticker, description) VALUES ('Noku', 'NOKU', 'Noku');
INSERT INTO currencies (name, ticker, description) VALUES ('BuySell', 'BULL', 'BuySell');
INSERT INTO currencies (name, ticker, description) VALUES ('Atletico De Madrid Fan Token', 'ATM', 'Atletico De Madrid Fan Token');
INSERT INTO currencies (name, ticker, description) VALUES ('42-coin', '42', '42-coin');
INSERT INTO currencies (name, ticker, description) VALUES ('IoT Chain', 'ITC', 'IoT Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('Valobit', 'VBIT', 'Valobit');
INSERT INTO currencies (name, ticker, description) VALUES ('Quasarcoin', 'QAC', 'Quasarcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('SIX', 'SIX', 'SIX');
INSERT INTO currencies (name, ticker, description) VALUES ('Kira Network', 'KEX', 'Kira Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Apple', 'mAAPL', 'Mirrored Apple');
INSERT INTO currencies (name, ticker, description) VALUES ('Alpha Quark Token', 'AQT', 'Alpha Quark Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Centaur', 'CNTR', 'Centaur');
INSERT INTO currencies (name, ticker, description) VALUES ('nDEX', 'NDX', 'nDEX');
INSERT INTO currencies (name, ticker, description) VALUES ('SmartCredit Token', 'SMARTCREDIT', 'SmartCredit Token');
INSERT INTO currencies (name, ticker, description) VALUES ('SingularDTV', 'SNGLS', 'SingularDTV');
INSERT INTO currencies (name, ticker, description) VALUES ('Dentacoin', 'DCN', 'Dentacoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Cryptocean', 'CRON', 'Cryptocean');
INSERT INTO currencies (name, ticker, description) VALUES ('AS Roma Fan Token', 'ASR', 'AS Roma Fan Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Hyperion', 'HYN', 'Hyperion');
INSERT INTO currencies (name, ticker, description) VALUES ('Orient Walt', 'HTDF', 'Orient Walt');
INSERT INTO currencies (name, ticker, description) VALUES ('Swapcoinz', 'SPAZ', 'Swapcoinz');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Tesla', 'mTSLA', 'Mirrored Tesla');
INSERT INTO currencies (name, ticker, description) VALUES ('DEAPcoin', 'DEP', 'DEAPcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Amazon', 'mAMZN', 'Mirrored Amazon');
INSERT INTO currencies (name, ticker, description) VALUES ('Odyssey', 'OCN', 'Odyssey');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Netflix', 'mNFLX', 'Mirrored Netflix');
INSERT INTO currencies (name, ticker, description) VALUES ('Pluton', 'PLU', 'Pluton');
INSERT INTO currencies (name, ticker, description) VALUES ('Lightning Bitcoin', 'LBTC', 'Lightning Bitcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Zano', 'ZANO', 'Zano');
INSERT INTO currencies (name, ticker, description) VALUES ('HOLD', 'HOLD', 'HOLD');
INSERT INTO currencies (name, ticker, description) VALUES ('Safe Haven', 'SHA', 'Safe Haven');
INSERT INTO currencies (name, ticker, description) VALUES ('Kebab Token', 'KEBAB', 'Kebab Token');
INSERT INTO currencies (name, ticker, description) VALUES ('PolySwarm', 'NCT', 'PolySwarm');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored iShares Gold Trust', 'mIAU', 'Mirrored iShares Gold Trust');
INSERT INTO currencies (name, ticker, description) VALUES ('Cardstack', 'CARD', 'Cardstack');
INSERT INTO currencies (name, ticker, description) VALUES ('DAOstack', 'GEN', 'DAOstack');
INSERT INTO currencies (name, ticker, description) VALUES ('OG Fan Token', 'OG', 'OG Fan Token');
INSERT INTO currencies (name, ticker, description) VALUES ('United Traders Token', 'UTT', 'United Traders Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Bitrue Coin', 'BTR', 'Bitrue Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Mobius', 'MOBI', 'Mobius');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Invesco QQQ Trust', 'mQQQ', 'Mirrored Invesco QQQ Trust');
INSERT INTO currencies (name, ticker, description) VALUES ('Pillar', 'PLR', 'Pillar');
INSERT INTO currencies (name, ticker, description) VALUES ('Covesting', 'COV', 'Covesting');
INSERT INTO currencies (name, ticker, description) VALUES ('UCA Coin', 'UCA', 'UCA Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('SmartMesh', 'SMT', 'SmartMesh');
INSERT INTO currencies (name, ticker, description) VALUES ('TriumphX', 'TRIX', 'TriumphX');
INSERT INTO currencies (name, ticker, description) VALUES ('SunContract', 'SNC', 'SunContract');
INSERT INTO currencies (name, ticker, description) VALUES ('Monero Classic', 'XMC', 'Monero Classic');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Twitter', 'mTWTR', 'Mirrored Twitter');
INSERT INTO currencies (name, ticker, description) VALUES ('Aragon Court', 'ANJ', 'Aragon Court');
INSERT INTO currencies (name, ticker, description) VALUES ('DEJAVE', 'DJV', 'DEJAVE');
INSERT INTO currencies (name, ticker, description) VALUES ('All Sports', 'SOC', 'All Sports');
INSERT INTO currencies (name, ticker, description) VALUES ('Counterparty', 'XCP', 'Counterparty');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored iShares Silver Trust', 'mSLV', 'Mirrored iShares Silver Trust');
INSERT INTO currencies (name, ticker, description) VALUES ('SONM', 'SNM', 'SONM');
INSERT INTO currencies (name, ticker, description) VALUES ('FREE Coin', 'FREE', 'FREE Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('PlayFuel', 'PLF', 'PlayFuel');
INSERT INTO currencies (name, ticker, description) VALUES ('ELYSIA', 'EL', 'ELYSIA');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Alibaba', 'mBABA', 'Mirrored Alibaba');
INSERT INTO currencies (name, ticker, description) VALUES ('Diamond Platform Token', 'DPT', 'Diamond Platform Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Goldcoin', 'GLC', 'Goldcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored Microsoft', 'mMSFT', 'Mirrored Microsoft');
INSERT INTO currencies (name, ticker, description) VALUES ('AIDUS TOKEN', 'AIDUS', 'AIDUS TOKEN');
INSERT INTO currencies (name, ticker, description) VALUES ('Origin Dollar', 'OUSD', 'Origin Dollar');
INSERT INTO currencies (name, ticker, description) VALUES ('T.OS', 'TOSC', 'T.OS');
INSERT INTO currencies (name, ticker, description) VALUES ('Credits', 'CS', 'Credits');
INSERT INTO currencies (name, ticker, description) VALUES ('BitCore', 'BTX', 'BitCore');
INSERT INTO currencies (name, ticker, description) VALUES ('Crypto Village Accelerator', 'CVA', 'Crypto Village Accelerator');
INSERT INTO currencies (name, ticker, description) VALUES ('Darwinia Commitment Token', 'KTON', 'Darwinia Commitment Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored United States Oil Fund', 'mUSO', 'Mirrored United States Oil Fund');
INSERT INTO currencies (name, ticker, description) VALUES ('Breezecoin', 'BRZE', 'Breezecoin');
INSERT INTO currencies (name, ticker, description) VALUES ('BitMart Token', 'BMX', 'BitMart Token');
INSERT INTO currencies (name, ticker, description) VALUES ('RigoBlock', 'GRG', 'RigoBlock');
INSERT INTO currencies (name, ticker, description) VALUES ('Emercoin', 'EMC', 'Emercoin');
INSERT INTO currencies (name, ticker, description) VALUES ('Minter Network', 'BIP', 'Minter Network');
INSERT INTO currencies (name, ticker, description) VALUES ('ColossusXT', 'COLX', 'ColossusXT');
INSERT INTO currencies (name, ticker, description) VALUES ('Valor Token', 'VALOR', 'Valor Token');
INSERT INTO currencies (name, ticker, description) VALUES ('TEMCO', 'TEMCO', 'TEMCO');
INSERT INTO currencies (name, ticker, description) VALUES ('SpankChain', 'SPANK', 'SpankChain');
INSERT INTO currencies (name, ticker, description) VALUES ('Raven Protocol', 'RAVEN', 'Raven Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('MAP Protocol', 'MAP', 'MAP Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Penta', 'PNT', 'Penta');
INSERT INTO currencies (name, ticker, description) VALUES ('DragonVein', 'DVC', 'DragonVein');
INSERT INTO currencies (name, ticker, description) VALUES ('Neumark', 'NEU', 'Neumark');
INSERT INTO currencies (name, ticker, description) VALUES ('Diamond', 'DMD', 'Diamond');
INSERT INTO currencies (name, ticker, description) VALUES ('Mirrored ProShares VIX', 'mVIXY', 'Mirrored ProShares VIX');
INSERT INTO currencies (name, ticker, description) VALUES ('Venus DAI', 'vDAI', 'Venus DAI');
INSERT INTO currencies (name, ticker, description) VALUES ('Remme', 'REM', 'Remme');
INSERT INTO currencies (name, ticker, description) VALUES ('ScPrime', 'SCP', 'ScPrime');
INSERT INTO currencies (name, ticker, description) VALUES ('Game.com', 'GTC', 'Game.com');
INSERT INTO currencies (name, ticker, description) VALUES ('QuadrantProtocol', 'EQUAD', 'QuadrantProtocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Precium', 'PCM', 'Precium');
INSERT INTO currencies (name, ticker, description) VALUES ('FLETA', 'FLETA', 'FLETA');
INSERT INTO currencies (name, ticker, description) VALUES ('WeShow Token', 'WET', 'WeShow Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Ternio', 'TERN', 'Ternio');
INSERT INTO currencies (name, ticker, description) VALUES ('Blockchain Certified Data Token', 'BCDT', 'Blockchain Certified Data Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Nexty', 'NTY', 'Nexty');
INSERT INTO currencies (name, ticker, description) VALUES ('EOS Force', 'EOSC', 'EOS Force');
INSERT INTO currencies (name, ticker, description) VALUES ('BackPacker Coin', 'BPC', 'BackPacker Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('apM Coin', 'APM', 'apM Coin');
INSERT INTO currencies (name, ticker, description) VALUES ('Hyprr (Howdoo)', 'UDOO', 'Hyprr (Howdoo)');
INSERT INTO currencies (name, ticker, description) VALUES ('Flash', 'FLASH', 'Flash');
INSERT INTO currencies (name, ticker, description) VALUES ('Hydro Protocol', 'HOT', 'Hydro Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Chi Gastoken', 'CHI', 'Chi Gastoken');
INSERT INTO currencies (name, ticker, description) VALUES ('DeepBrain Chain', 'DBC', 'DeepBrain Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('Pundi X NEM', 'NPXSXEM', 'Pundi X NEM');
INSERT INTO currencies (name, ticker, description) VALUES ('PolkaBridge', 'PBR', 'PolkaBridge');
INSERT INTO currencies (name, ticker, description) VALUES ('Seigniorage Shares', 'SHARE', 'Seigniorage Shares');
INSERT INTO currencies (name, ticker, description) VALUES ('Callisto Network', 'CLO', 'Callisto Network');
INSERT INTO currencies (name, ticker, description) VALUES ('fyeth.finance', 'YETH', 'fyeth.finance');
INSERT INTO currencies (name, ticker, description) VALUES ('PANTHEON X', 'XPN', 'PANTHEON X');
INSERT INTO currencies (name, ticker, description) VALUES ('Genaro Network', 'GNX', 'Genaro Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Earneo', 'RNO', 'Earneo');
INSERT INTO currencies (name, ticker, description) VALUES ('NuBits', 'USNBT', 'NuBits');
INSERT INTO currencies (name, ticker, description) VALUES ('UnlimitedIP', 'UIP', 'UnlimitedIP');
INSERT INTO currencies (name, ticker, description) VALUES ('Safe', 'SAFE', 'Safe');
INSERT INTO currencies (name, ticker, description) VALUES ('Peculium', 'PCL', 'Peculium');
INSERT INTO currencies (name, ticker, description) VALUES ('BIDR', 'BIDR', 'BIDR');
INSERT INTO currencies (name, ticker, description) VALUES ('MediShares', 'MDS', 'MediShares');
INSERT INTO currencies (name, ticker, description) VALUES ('Phore', 'PHR', 'Phore');
INSERT INTO currencies (name, ticker, description) VALUES ('QuickX Protocol', 'QCX', 'QuickX Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('Verasity', 'VRA', 'Verasity');
INSERT INTO currencies (name, ticker, description) VALUES ('ProximaX', 'XPX', 'ProximaX');
INSERT INTO currencies (name, ticker, description) VALUES ('Fuse Network', 'FUSE', 'Fuse Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Nord Finance', 'NORD', 'Nord Finance');
INSERT INTO currencies (name, ticker, description) VALUES ('ZIMBOCASH', 'ZASH', 'ZIMBOCASH');
INSERT INTO currencies (name, ticker, description) VALUES ('Origo', 'OGO', 'Origo');
INSERT INTO currencies (name, ticker, description) VALUES ('NewYorkCoin', 'NYC', 'NewYorkCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('ODEM', 'ODE', 'ODEM');
INSERT INTO currencies (name, ticker, description) VALUES ('Amoveo', 'VEO', 'Amoveo');
INSERT INTO currencies (name, ticker, description) VALUES ('Level01', 'LVX', 'Level01');
INSERT INTO currencies (name, ticker, description) VALUES ('Atlas Protocol', 'ATP', 'Atlas Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('PressOne', 'PRS', 'PressOne');
INSERT INTO currencies (name, ticker, description) VALUES ('Skrumble Network', 'SKM', 'Skrumble Network');
INSERT INTO currencies (name, ticker, description) VALUES ('CoTrader', 'COT', 'CoTrader');
INSERT INTO currencies (name, ticker, description) VALUES ('Parachute', 'PAR', 'Parachute');
INSERT INTO currencies (name, ticker, description) VALUES ('Abyss', 'ABYSS', 'Abyss');
INSERT INTO currencies (name, ticker, description) VALUES ('BUX Token', 'BUX', 'BUX Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Litecoin Cash', 'LCC', 'Litecoin Cash');
INSERT INTO currencies (name, ticker, description) VALUES ('Lykke', 'LKK', 'Lykke');
INSERT INTO currencies (name, ticker, description) VALUES ('Fatcoin', 'FAT', 'Fatcoin');
INSERT INTO currencies (name, ticker, description) VALUES ('MIR COIN', 'MIR', 'MIR COIN');
INSERT INTO currencies (name, ticker, description) VALUES ('VeriDocGlobal', 'VDG', 'VeriDocGlobal');
INSERT INTO currencies (name, ticker, description) VALUES ('Rapidz', 'RPZX', 'Rapidz');
INSERT INTO currencies (name, ticker, description) VALUES ('Digix Gold Token', 'DGX', 'Digix Gold Token');
INSERT INTO currencies (name, ticker, description) VALUES ('Zel', 'ZEL', 'Zel');
INSERT INTO currencies (name, ticker, description) VALUES ('Dune Network', 'DUN', 'Dune Network');
INSERT INTO currencies (name, ticker, description) VALUES ('GAPS', 'GAP', 'GAPS');
INSERT INTO currencies (name, ticker, description) VALUES ('Egretia', 'EGT', 'Egretia');
INSERT INTO currencies (name, ticker, description) VALUES ('Tripio', 'TRIO', 'Tripio');
INSERT INTO currencies (name, ticker, description) VALUES ('ALQO', 'XLQ', 'ALQO');
INSERT INTO currencies (name, ticker, description) VALUES ('qiibee', 'QBX', 'qiibee');
INSERT INTO currencies (name, ticker, description) VALUES ('Zenfuse', 'ZEFU', 'Zenfuse');
INSERT INTO currencies (name, ticker, description) VALUES ('bitCNY', 'BITCNY', 'bitCNY');
INSERT INTO currencies (name, ticker, description) VALUES ('dForce USDx', 'USDX', 'dForce USDx');
INSERT INTO currencies (name, ticker, description) VALUES ('MASQ', 'MASQ', 'MASQ');
INSERT INTO currencies (name, ticker, description) VALUES ('OKCash', 'OK', 'OKCash');
INSERT INTO currencies (name, ticker, description) VALUES ('BitGreen', 'BITG', 'BitGreen');
INSERT INTO currencies (name, ticker, description) VALUES ('MyWish', 'WISH', 'MyWish');
INSERT INTO currencies (name, ticker, description) VALUES ('Nsure.Network', 'NSURE', 'Nsure.Network');
INSERT INTO currencies (name, ticker, description) VALUES ('VNX Exchange', 'VNXLU', 'VNX Exchange');
INSERT INTO currencies (name, ticker, description) VALUES ('Traceability Chain', 'TAC', 'Traceability Chain');
INSERT INTO currencies (name, ticker, description) VALUES ('Banano', 'BAN', 'Banano');
INSERT INTO currencies (name, ticker, description) VALUES ('NoLimitCoin', 'NLC2', 'NoLimitCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('CasinoCoin', 'CSC', 'CasinoCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('CryptoPing', 'PING', 'CryptoPing');
INSERT INTO currencies (name, ticker, description) VALUES ('Dev Protocol', 'DEV', 'Dev Protocol');
INSERT INTO currencies (name, ticker, description) VALUES ('FinNexus', 'FNX', 'FinNexus');
INSERT INTO currencies (name, ticker, description) VALUES ('DMM: Governance', 'DMG', 'DMM: Governance');
INSERT INTO currencies (name, ticker, description) VALUES ('Growth DeFi', 'GRO', 'Growth DeFi');
INSERT INTO currencies (name, ticker, description) VALUES ('Blocery', 'BLY', 'Blocery');
INSERT INTO currencies (name, ticker, description) VALUES ('Minereum', 'MNE', 'Minereum');
INSERT INTO currencies (name, ticker, description) VALUES ('Smartlands Network', 'SLT', 'Smartlands Network');
INSERT INTO currencies (name, ticker, description) VALUES ('Spaceswap', 'MILK2', 'Spaceswap');
INSERT INTO currencies (name, ticker, description) VALUES ('DECOIN', 'DTEP', 'DECOIN');
INSERT INTO currencies (name, ticker, description) VALUES ('ToaCoin', 'TOA', 'ToaCoin');
INSERT INTO currencies (name, ticker, description) VALUES ('HitChain', 'HIT', 'HitChain');
INSERT INTO currencies (name, ticker, description) VALUES ('BOLT', 'BOLT', 'BOLT');
INSERT INTO currencies (name, ticker, description) VALUES ('Aeon', 'AEON', 'Aeon');
INSERT INTO currencies (name, ticker, description) VALUES ('e-Gulden', 'EFL', 'e-Gulden');
INSERT INTO currencies (name, ticker, description) VALUES ('YOU COIN', 'YOU', 'YOU COIN');
INSERT INTO currencies (name, ticker, description) VALUES ('Offshift', 'XFT', 'Offshift');
INSERT INTO currencies (name, ticker, description) VALUES ('OTOCASH', 'OTO', 'OTOCASH');
INSERT INTO currencies (name, ticker, description) VALUES ('ZClassic', 'ZCL', 'ZClassic');
INSERT INTO currencies (name, ticker, description) VALUES ('DePay', 'DEPAY', 'DePay');
INSERT INTO currencies (name, ticker, description) VALUES ('XYO', 'XYO', 'XYO');
INSERT INTO currencies (name, ticker, description) VALUES ('UGAS', 'UGAS', 'UGAS');
