coin:
  paprika:
    endpoint: https://api.coinpaprika.com/v1/
logging:
  level:
    org:
      hibernate: WARN
      springframework: WARN
zipline:
  app:
    api:
      url: https://zipline.link
    jwtExpirationMs: 86400000
    jwtSecret: ziplineSecretKey
server:
  port: 8081
spring:
  datasource:
    password: admin!
    url: jdbc:postgresql://localhost:5432/db
#    url: jdbc:postgresql://64.225.96.200:5432/db
#    url: jdbc:postgresql://db:5432/db
    username: postgres
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  mail:
    host: smtp.gmail.com
    password: hV2qH9fY9lZ5sI4kN5uS
    port: 465
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
        smtps:
          auth: true
          starttls:
            enable: true
          timeout: 8000
        transport:
          protocol: smtps
    protocol: smtps
    username: ziplinelink@gmail.com
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      export:
        prometheus:
          enabled: true
      application: zipline-backend
cointelegraph:
  urlRSS: https://cointelegraph.com/rss
